
# Partially Generated by Gemini 4/7/2026
# Prompt: "How could I auto run an executable where my executable is mySAT and takes one argument in the form of a .cnf"

#!/bin/bash

# Define the folder containing the benchmarks
BENCHMARK_DIR="Benchmark Files/uf20-91"
SOLVER="SAT Solver/mySAT"
OUTPUT_FILE="test_results.txt"

# Clear the old output file
> "$OUTPUT_FILE"

echo "Starting Benchmark Run..."

# Loop through every .cnf file
for file in "$BENCHMARK_DIR"/*.cnf; do
    echo "Running $file..."
    
    # Write the file name to the text file
    echo "--- $file ---" >> "$OUTPUT_FILE"
    
    # Run the solver (wrapped in quotes to handle any folder spaces!)
    "./$SOLVER" "$file" >> "$OUTPUT_FILE"
    
    # Add a blank line for readability
    echo "" >> "$OUTPUT_FILE"
done

echo "Done $OUTPUT_FILE"