
# Partially Generated by Gemini 4/30/2026
# Prompt: "Adapt my current executable to save output to a csv and log runtime and memory usage"

#!/bin/bash

# Define the folders and files
BENCHMARK_DIR="Benchmark Files/uuf50-218"
SOLVER="SAT Solver/mySAT"
CSV_FILE="data/test_results.csv"

# 1. Update the CSV header to include the new Internal Solve Time column
echo "Filename,Result,Internal Solve Time (s),Total System Time (s),Peak Memory (KB)" > "$CSV_FILE"

echo "Starting Benchmark Run..."

# Loop through every .cnf file
for file in "$BENCHMARK_DIR"/*.cnf; do
    echo "Running $file..."
    
    # Get just the file name
    base_name=$(basename "$file")
    
    # Run the solver and the time command NOTE Add "--dlis" after "$file" for dlis tests
    /usr/bin/time -f "%e,%M" -o temp_time.txt "./$SOLVER" "$file" > temp_out.txt
    
    # Parse the SAT/UNSAT result
    result=$(grep "RESULT:" temp_out.txt | cut -d':' -f2)
    
    # --- NEW: Parse your internal C++ Solve Time ---
    # 1. grep "Solve Time:" finds the line (e.g., "Solve Time:0.045 seconds")
    # 2. cut -d':' -f2 grabs everything after the colon ("0.045 seconds")
    # 3. awk '{print $1}' grabs just the first word/number ("0.045")
    solve_time=$(grep "Solve Time:" temp_out.txt | cut -d':' -f2 | awk '{print $1}')
    
    # Read the formatted system time and memory string
    time_and_memory=$(cat temp_time.txt)
    
    # Append all the variables together as a single row in the CSV
    echo "$base_name,$result,$solve_time,$time_and_memory" >> "$CSV_FILE"

done

# Clean up the temporary files
rm temp_out.txt temp_time.txt

echo "Done! Benchmark data saved to $CSV_FILE"