# Generated by Google Gemini 5/4/2026
# "Given this .sh file please give me a new .sh that will run batch sizes of 100 and start from where it left off"


#!/bin/bash

# Define the folders and files
BENCHMARK_DIR="Benchmark Files/uuf100-430"
SOLVER="SAT Solver/mySAT"
CSV_FILE="data/test_results.csv"

# --- NEW: Define how many files to run per batch ---
BATCH_SIZE=100

# 1. Create the CSV and header ONLY if it doesn't already exist
if [ ! -f "$CSV_FILE" ]; then
    echo "Filename,Result,Internal Solve Time (s),Total System Time (s),Peak Memory (KB)" > "$CSV_FILE"
fi

# 2. Count how many files have already been processed (subtract 1 for the header)
if [ -f "$CSV_FILE" ]; then
    PROCESSED_COUNT=$(tail -n +2 "$CSV_FILE" | wc -l)
else
    PROCESSED_COUNT=0
fi

echo "Found $PROCESSED_COUNT files already processed. Resuming..."

# 3. Load all .cnf files into an array so we can index them
files=("$BENCHMARK_DIR"/*.cnf)
TOTAL_FILES=${#files[@]}

# Calculate our start and end indices for this specific batch
START_IDX=$PROCESSED_COUNT
END_IDX=$((START_IDX + BATCH_SIZE))

# Don't go past the total number of files
if [ "$END_IDX" -gt "$TOTAL_FILES" ]; then
    END_IDX=$TOTAL_FILES
fi

# Check if we are already done
if [ "$START_IDX" -ge "$TOTAL_FILES" ]; then
    echo "All $TOTAL_FILES files have been successfully processed!"
    exit 0
fi

echo "Processing batch: Files $START_IDX to $((END_IDX - 1))..."

# 4. Loop through only the specific slice of files for this batch
for (( i=$START_IDX; i<$END_IDX; i++ )); do
    file="${files[$i]}"
    base_name=$(basename "$file")
    
    echo "[$((i + 1))/$TOTAL_FILES] Running $base_name..."
    
    # Run the solver and the time command
    /usr/bin/time -f "%e,%M" -o temp_time.txt "./$SOLVER" "$file" > temp_out.txt
    
    # Parse the SAT/UNSAT result
    result=$(grep "RESULT:" temp_out.txt | cut -d':' -f2)
    
    # Parse your internal C++ Solve Time
    solve_time=$(grep "Solve Time:" temp_out.txt | cut -d':' -f2 | awk '{print $1}')
    
    # Read the formatted system time and memory string
    time_and_memory=$(cat temp_time.txt)
    
    # Append to the CSV immediately so data is saved even if the server crashes
    echo "$base_name,$result,$solve_time,$time_and_memory" >> "$CSV_FILE"
done

# Clean up the temporary files
rm -f temp_out.txt temp_time.txt

echo "Batch complete! Saved to $CSV_FILE."
echo "Run this script again to process the next $BATCH_SIZE files."